Creating file for Ezoic integrated sites
GoogleChrome/lighthouse-stack-packs pull request #19
Opened 2019-05-29 17:12 UTC by jbauer23

[Ezoic](https://www.ezoic.com) is a Google Certified Publishing Partner. Our Partner Manager is Mauricio Geutierrez (molvera@google.com), and he told us about this program. 

Our service for publishers has improves ad management, site speed, and a few other aspects of their site. Because one of our features improves site speed by fixing issues with these audits, we'd like to submit a stack pack so that publishers on our system can be notified to turn on relevant features. I've submitted recommendations for 13 audits and we have plans to support at least 2 more in the near future. 

To detect if a site is using Ezoic, look for the X-Middleton-Display header. It's presences indicates that a site is running on our platform.

2020-03-30 16:09 UTC, housseindjirdeh commented
Sorry for taking so long to get to this! We've been prioritizing other CMS/frameworks that have more usage, but we can definitely look to include this :)

Just two things:

1. Would you be able to add the detection to the [library detector](https://github.com/johnmichel/Library-Detector-for-Chrome/blob/master/library/libraries.js)? (separate repo)
2. Can you update this to follow the [newer format](https://github.com/GoogleChrome/lighthouse-stack-packs/blob/master/packs/drupal.js) we have (`.js` files with an export)

2020-05-19 15:07 UTC, housseindjirdeh commented
Friendly ping @jbauer23! If you can't make any of the changes, no worries and let me know :)

2020-05-19 15:52 UTC, jbauer23 commented
Sorry, been crazy and this got lost in the shuffle. I'll take a look this week.

2020-05-20 16:12 UTC, housseindjirdeh commented
No rush at all, the apologies are all on my end for taking so long to get to this

2020-05-20 17:30 UTC, jbauer23 commented
Updating the detector will take a little work on our end, so I'm passing this off to someone else on the team to finish up.

2021-11-24 00:22 UTC, connorjclark commented
Hi @jbauer23, if you are still interested: FYI the library detector runs inside a page, thus it cannot rely on headers. Is there some JS global that this CMS exposes? If not, could you add one?

2021-11-30 23:10 UTC, jbauer23 commented
Hey @connorjclark I've got our pack updated to the current format here, but it needs approval from a maintainer. 

We also have another PR that has the updates to the detector library here: https://github.com/johnmichel/Library-Detector-for-Chrome/pull/193

2021-12-09 02:25 UTC, connorjclark requested changes

2021-12-09 02:25 UTC, connorjclark commented on packs/ezoic.js
> +// Minify with https://jakearchibald.github.io/svgomg/
you can delete all the meta-comments above this line

2021-12-09 02:25 UTC, connorjclark commented on packs/ezoic.js
> +  'uses-optimized-images': 'Using [Ezoic Leap](https://pubdash.ezoic.com/speed) and enabling `Next-Gen Formats` will convert images to WebP.',
for this string and all others, change up the grammar to be more like:

`Use Ezoic Leap and enable `Some-Feature` to convert images to WebP`

basically, avoid present participles (adding -ing to verbs) and prefer the normal form of verb, as it tends to simplify the language

2021-12-09 02:25 UTC, connorjclark commented on packs/ezoic.js
> +  'redirects': '',
just delete these empty ones

2021-12-09 18:11 UTC, jbauer23 commented on packs/ezoic.js
> +  'redirects': '',
I've made those changes, thanks.

2021-12-09 18:18 UTC, connorjclark commented on packs/ezoic.js
> +  'uses-rel-preconnect': 'Use [Ezoic Leap](https://pubdash.ezoic.com/speed) and enable `Pre-Connect Origins` to automatically add preconnect resource hints to establish early connections to important
```suggestion
  'uses-rel-preconnect': 'Use [Ezoic Leap](https://pubdash.ezoic.com/speed) and enable `Pre-Connect Origins` to automatically add `preconnect` resource hints to establish early connections to important third-party origins.',
```

2021-12-09 18:19 UTC, connorjclark commented on packs/ezoic.js
> +  'font-display': 'Use [Ezoic Leap](https://pubdash.ezoic.com/speed) and enable `Optimize Fonts` to automatically leverage the font-display CSS feature to ensure text is user-visible while webfonts a
```suggestion
  'font-display': 'Use [Ezoic Leap](https://pubdash.ezoic.com/speed) and enable `Optimize Fonts` to automatically leverage the `font-display` CSS feature to ensure text is user-visible while webfonts are loading.',
```

2022-01-27 23:38 UTC, merged