feat: Add Stack Pack for Gatsby
GoogleChrome/lighthouse-stack-packs pull request #93
Opened 2023-04-17 12:36 UTC by LekoArts

Hi, Gatsby maintainer here 👋 

This PR adds a Stack Pack for Gatsby, mainly recommending our [Image Plugin](https://www.gatsbyjs.com/docs/how-to/images-and-media/using-gatsby-plugin-image/) and [Script API](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-script/).

I reused some wording from the Next.js PR: https://github.com/GoogleChrome/lighthouse-stack-packs/pull/66

2023-04-17 18:04 UTC, connorjclark requested changes
There's a failing test to address FYI

2023-04-18 05:34 UTC, LekoArts commented on packs/gatsby.js
> +  'unused-css-rules': 'Consider setting up `PurgeCSS` in `Gatsby` configuration to remove unused rules from stylesheets. [Learn more](https://purgecss.com/plugins/gatsby.html).',
This was copied from the Next.js piece - but I changed it to "use" now 👍

2023-05-03 18:38 UTC, connorjclark commented on packs/gatsby.js
> +const icon = `data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 28 28"><circle cx="14" cy="14" r="14" fill="#639"/><path fill="#fff" d="M6.2 21.8C4.1 19.7 3 16.9 3 14.2L13.9 25c
```suggestion
const icon = `data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 28 28"><circle cx="14" cy="14" r="14" fill="%23639"/><path fill="%23fff" d="M6.2 21.8C4.1 19.7 3 16.9 3 14.2L13.9 25c-2.8-.1-5.6-1.1-7.7-3.2zm10.2 2.9L3.3 11.6C4.4 6.7 8.8 3 14 3c3.7 0 6.9 1.8 8.9 4.5l-1.5 1.3C19.7 6.5 17 5 14 5c-3.9 0-7.2 2.5-8.5 6L17 22.5c2.9-1 5.1-3.5 5.8-6.5H18v-2h7c0 5.2-3.7 9.6-8.6 10.7z"/></svg>`;
```

2023-05-03 18:41 UTC, connorjclark approved these changes

2023-05-03 18:41 UTC, merged

2023-05-03 18:42 UTC, connorjclark commented
Thanks! Expect this in the next Lighthouse release.

2023-05-04 06:21 UTC, LekoArts commented
Awesome, thank you!